{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart-ci-example.serviceAccountName" . }}
  labels:
{{ include "chart-ci-example.labels" . | nindent 4 }}
{{- end -}}
